apiVersion: v2
name: verity
description: Container image registry managed by verity
type: application
version: 0.1.0
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: oci://ghcr.io/prometheus-community/charts
