name: Request New Image
description: Request a standalone Docker image to be patched and published
title: "feat: add "
labels: ["new-image"]
body:
  - type: input
    id: name
    attributes:
      label: Image name
      description: A short name for this image (e.g. nginx, redis)
      placeholder: nginx
    validations:
      required: true

  - type: input
    id: repository
    attributes:
      label: Image repository
      description: The image repository path (e.g. library/nginx)
      placeholder: library/nginx
    validations:
      required: true

  - type: input
    id: tag
    attributes:
      label: Image tag
      description: The tag to pin (e.g. 1.25.0)
      placeholder: "1.25.0"
    validations:
      required: true

  - type: input
    id: registry
    attributes:
      label: Image registry
      description: The container registry (e.g. docker.io)
      placeholder: docker.io
    validations:
      required: true
