name: Request New Chart
description: Request a new Helm chart to be patched and published
title: "Add chart: "
labels: ["new-chart"]
body:
  - type: input
    id: name
    attributes:
      label: Chart name
      description: The name of the Helm chart (e.g. prometheus, grafana)
      placeholder: prometheus
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Chart version
      description: The version to pin (e.g. 25.8.0)
      placeholder: "25.8.0"
    validations:
      required: true

  - type: input
    id: repository
    attributes:
      label: Chart repository
      description: OCI or HTTP repository URL
      placeholder: oci://ghcr.io/prometheus-community/charts
    validations:
      required: true
